version: "3.9"

networks:
  datareservoir-network:
    driver: bridge
    
services:
  datareservoir-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
    ports:
      - "3306:3306"
    networks:
      - datareservoir-network
      
  datareservoir-redis:
    image: redis:6.2.1-alpine
    networks:
      - datareservoir-network
      
  datareservoir-all:
    image: datareservoir-all
    command: ["/wait-for-it.sh", "datareservoir-mysql:33306", "-t", "15", "--", "java", "-jar", "project.jar"]
    environment:
      VIRTUAL_HOST: localhost
      VIRTUAL_PORT: 8080
      DB_HOST: datareservoir-mysql
      HOST: localhost:8080
      SPRING_PROFILES_ACTIVE: development
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: DEBUG
      SPRING_SESSION_STORE_TYPE: redis
      SPRING_REDIS_HOST: datareservoir-redis
      DATARESERVOIR_RESOURCE_BASE_USERNAME: base-station
      DATARESERVOIR_RESOURCE_BASE_PASSWORD: base123
      DATARESERVOIR_RESOURCE_CLIENT_USERNAME: client-station
      DATARESERVOIR_RESOURCE_CLIENT_PASSWORD: client123
      DATARESERVOIR_RESOURCE_ADMIN_USERNAME: admin-client
      DATARESERVOIR_RESOURCE_ADMIN_PASSWORD: admin123
      DATARESERVOIR_CLIENT_WEB_SERVICE_USERNAME: brenoClient
      DATARESERVOIR_CLIENT_WEB_SERVICE_PASSWORD: 123
      DATARESERVOIR_CLIENT_ADMIN_USERNAME: brenoAdmin
      DATARESERVOIR_CLIENT_ADMIN_PASSWORD: 123
      DATARESERVOIR_SECURITY_USER: breno
      DATARESERVOIR_SECURITY_PASSWORD: $$2a$$04$$ga/m5guarUABgAawe5fS0e5FpCql2lG7.d2Var3qnJm69fNTo6I4y
      DATARESERVOIR_AUTHORIZATION_AUTH_USERNAME: brenoAdmin
      DATARESERVOIR_AUTHORIZATION_AUTH_PASSWORD: 123
      DATARESERVOIR_AUTHORIZATION_AUTH_CLIENT_USERNAME: admin-client
      DATARESERVOIR_AUTHORIZATION_AUTH_CLIENT_PASSWORD: admin123
    expose:
      - "8080"
    networks:
      - datareservoir-network
    depends_on:
      - datareservoir-mysql
      
  datareservoir-proxy:
    build: nginxproxy/nginx-proxy
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - datareservoir-network
    depends_on:
      - datareservoir-all